timeout: 10
stressors:
  - stressor: vm
    workers: 2
    vm-bytes: 10g
  - stressor: cpu
    workers: 2
    cpu-method: all
  - stressor: hdd
    workers: 2
    hdd-write-size: 4M
    hdd-bytes: 1G
  - stressor: matrix
    workers: 2
  - stressor: mq
    workers: 2
